language: node_js
node_js: "10.9.0"
addons:
  chrome: stable
  postgresql: "11.2"
services:
  - postgresql
before_script:
  - psql --version
  - psql -c 'CREATE DATABASE connect;' -U postgres
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
  - npm install -g grunt-cli
  - cp sample.env .env
