language: node_js
node_js:
  - "10.9.0"
sudo: required
addons:
  chrome: stable
  postgresql: "11"
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11
env:
  global:
    - PGPORT=5433
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE connect;' -U postgres;
before_install:
  - npm install -g grunt-cli
  - sleep 5 # give time for mongo to wake up: https://docs.travis-ci.com/user/database-setup/#mongodb
  - cp sample.env .env
