# This official base image contains node.js and npm
FROM node:11
# Copy the application files
RUN mkdir app
WORKDIR /app
COPY /app /app/app
COPY /package.json /app/package.json
COPY /server.ts /app/server.ts
COPY /tsconfig.json /app/tsconfig.json
COPY /nodemon.json /app/nodemon.json
COPY /.env /app/.env
RUN npm install

# Make the application run when running the container
CMD ["npm", "run", "start"]
