version: "3"

services:
    db:
        image: mongo:2
        expose:
            - "27017"
        ports:
            - "27017:27017"
    app:
        build: ./
        depends_on:
            - db
        env_file:
            - .env
        ports:
            - "3000:3000"

