version: "3"

services:
  springroll-connect:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: ./docker/dev.DockerFile
    volumes:
      - ./app:/app
    expose:
      - 3000
    ports:
      - 3000:3000
  postgres:
    image: postgres:11.1
    expose:
      - "5432"
    ports:
      - "5432:5432"
